version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/app
    environment:
      DOCKER_REPO: stefanwalther/docker-test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      #- add_ssh_keys
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: ./scripts/cci2-install-docker-client.sh 17.04.0-ce
      - run:
          name: Update version tag
          command: |
            set -e
            VER=$(node -e "console.log(require('./package.json').version)")
            # If a git tag is not set or if the tag does not match release pattern e.g. v1.2.3, then add the cci build number to the version.
            RELEASE_PATTERN="v[0-9].*"
            if [[ -z "${CIRCLE_TAG}" || ! $CIRCLE_TAG =~ $RELEASE_PATTERN ]]; then
              VER+="-$CIRCLE_BUILD_NUM"
              npm version $VER --no-git-tag-version
            fi
            echo "$VER" > ./version.txt
      - run:
          name: Build Docker image
          command: |
            VER=$(cat ./version.txt)
            docker build -t $DOCKER_REPO:$VER .

